### ISSUE TITLE
https://www.airpair.com/node.js/posts/top-10-mistakes-node-developers-make

### ISSUE THREAD

**Issue by jtyjty99999** [FrontendMagazine/Works#8]
https://www.airpair.com/node.js/posts/top-10-mistakes-node-developers-make

**Comment by jtyjty99999** [comment]
翻译完毕，大约周一8:20发。。。

**Comment by island205** [comment]
@jtyjty99999 把译文提交到github上来吧，按照我们之前的惯例，让对方看看有没有什么问题。

**Comment by jtyjty99999** [comment]
@island205 ok,我明天提交下
